package com.depakto.classes.help.api;

public enum ClientProperty implements Property {
    CID(false),
    CLIENT_AWAY(true),
    CLIENT_AWAY_MESSAGE(true),
    CLIENT_BASE64HASHCLIENTUID(false),
    CLIENT_CHANNEL_GROUP_ID(true),
    CLIENT_CHANNEL_GROUP_INHERITED_CHANNEL_ID(true),
    CLIENT_COUNTRY(true),
    CLIENT_CREATED(false),
    CLIENT_DATABASE_ID(true),
    CLIENT_DEFAULT_CHANNEL(false),
    CLIENT_DEFAULT_TOKEN(false),
    CLIENT_DESCRIPTION(true),
    CLIENT_FLAG_AVATAR(false),
    CLIENT_ICON_ID(true),
    CLIENT_IDLE_TIME(false),
    CLIENT_INPUT_HARDWARE(true),
    CLIENT_INPUT_MUTED(true),
    CLIENT_IS_CHANNEL_COMMANDER(true),
    CLIENT_IS_MUTED(true),
    CLIENT_IS_PRIORITY_SPEAKER(true),
    CLIENT_IS_RECORDING(true),
    CLIENT_IS_TALKER(true),
    CLIENT_LASTCONNECTED(false),
    CLIENT_LOGIN_NAME(false),
    CLIENT_META_DATA(true),
    CLIENT_MONTH_BYTES_DOWNLOADED(false),
    CLIENT_MONTH_BYTES_UPLOADED(false),
    CLIENT_NEEDED_SERVERQUERY_VIEW_POWER(true),
    CLIENT_NICKNAME(true),
    CLIENT_NICKNAME_PHONETIC(true),
    CLIENT_OUTPUT_HARDWARE(true),
    CLIENT_OUTPUT_MUTED(true),
    CLIENT_OUTPUTONLY_MUTED(true),
    CLIENT_PLATFORM(false),
    CLIENT_SERVERGROUPS(true),
    CLIENT_TALK_POWER(true),
    CLIENT_TALK_REQUEST(true),
    CLIENT_TALK_REQUEST_MSG(true),
    CLIENT_TOTAL_BYTES_DOWNLOADED(false),
    CLIENT_TOTAL_BYTES_UPLOADED(false),
    CLIENT_TOTALCONNECTIONS(false),
    CLIENT_TYPE(true),
    CLIENT_UNIQUE_IDENTIFIER(true),
    CLIENT_UNREAD_MESSAGES(true),
    CLIENT_VERSION(false),
    CONNECTION_BANDWIDTH_RECEIVED_LAST_MINUTE_TOTAL(false),
    CONNECTION_BANDWIDTH_RECEIVED_LAST_SECOND_TOTAL(false),
    CONNECTION_BANDWIDTH_SENT_LAST_MINUTE_TOTAL(false),
    CONNECTION_BANDWIDTH_SENT_LAST_SECOND_TOTAL(false),
    CONNECTION_BYTES_RECEIVED_TOTAL(false),
    CONNECTION_BYTES_SENT_TOTAL(false),
    CONNECTION_CLIENT_IP(false),
    CONNECTION_CONNECTED_TIME(false),
    CONNECTION_FILETRANSFER_BANDWIDTH_RECEIVED(false),
    CONNECTION_FILETRANSFER_BANDWIDTH_SENT(false),
    CONNECTION_PACKETS_RECEIVED_TOTAL(false),
    CONNECTION_PACKETS_SENT_TOTAL(false);
    
    private boolean changeable;

    private ClientProperty(boolean changeable) {
        this.changeable = changeable;
    }

    public String getName() {
        return name().toLowerCase();
    }

    public boolean isChangeable() {
        return this.changeable;
    }
}
